volumes:
  server-certs:
    driver: "local"

services:
  postgres:
    restart: unless-stopped
  graphql:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SESSION_SECURE=true
  server:
    restart: unless-stopped
    environment:
      - APP_DOMAINS=${APP_DOMAINS}
      - TLS=true
      - CERT_DIR=/srv/certs
      - SERVER_PORT=443 # is the default already, but defined for healtchecks
    volumes:
      - server-certs:/srv/certs
    ports:
      - 80:80
      - 443:443
  gotenberg:
    restart: unless-stopped
