version: "3"

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  graphql:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      - WATCH=true
  app:
    ports:
      - 80:80
