version: "3"

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  graphql:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WATCH=true
    ports:
      - ${GRAPHQL_PORT}:${GRAPHQL_PORT}
  server:
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  gotenberg:
    ports:
      - ${GOTENBERG_PORT}:${GOTENBERG_PORT}
