version: "3"

volumes:
  server-certs:
    driver: "local"

services:
  postgres:
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  graphql:
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SESSION_SECURE=true
      - WATCH=true
  server:
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DOMAINS=${APP_DOMAINS}
      - TLS=true
      - CERT_DIR=/srv/certs
    volumes:
      - server-certs:/srv/certs
    ports:
      - 80:80
      - 443:443
  gotenberg:
    restart: unless-stopped
