version: "3"
volumes:
  postgres-data:
    driver: "local"
networks:
  private:
    driver: "bridge"
  public:
    driver: "bridge"
services:
  postgres:
    image: bhidapa/heltin-postgres
    networks:
      - private
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  graphql:
    image: bhidapa/heltin-graphql
    networks:
      - private
      - public
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SCHEMAS=${POSTGRES_SCHEMAS}
      - GRAPHQL_ROUTE=/graphql
      - GRAPHIQL_ROUTE=/graphiql
      - JWT_POSTGRES_TYPE_IDENTIFIER=${JWT_POSTGRES_TYPE_IDENTIFIER}
      - PORT=${GRAPHQL_PORT}
    depends_on:
      - postgres
    restart: unless-stopped
