name: Build, push and deploy

on: workflow_dispatch

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v1
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          push: true

  deploy-bhidapa:
    name: Deploy to BHIDAPA
    environment: BHIDAPA
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup SSH identity
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_IDENTITY }}"
      - name: Create and use context
        run: |
          docker context create bhidapa --docker host=ssh://${{ secrets.USER }}@${{ secrets.HOST }}
          docker context use bhidapa
      - name: Pull
        run: docker compose pull
      - name: Down
        run: docker compose down
      # TODO: deploy database schema changes
      - name: Up
        env:
          APP_DOMAINS: ${{ secrets.APP_DOMAINS }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
