name: Deploy

on: workflow_dispatch

jobs:
  deploy-bhidapa:
    name: Deploy to BHIDAPA
    uses: bhidapa/heltin/.github/workflows/reusable-deploy-workflow.yml@main
    with:
      environment: BHIDAPA
    secrets: inherit
