name: Deploy

on: workflow_dispatch

jobs:
  deploy-bhidapa:
    name: Deploy to BHIDAPA
    environment: BHIDAPA
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup SSH identity
        run: |
          mkdir -p ~/.ssh && ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK
          ssh-add - <<< "${{ secrets.SSH_IDENTITY }}"
      - name: Create and use context
        run: |
          docker context create bhidapa --docker host=ssh://${{ secrets.USER }}@${{ secrets.HOST }}
          docker context use bhidapa
      - name: Pull
        run: docker compose pull
      - name: Down
        run: docker compose down || docker compose down # sometimes "down" fails, try 2 times
      # TODO: deploy database schema changes, is it even possible to automate?
      - name: Up
        env:
          APP_DOMAINS: ${{ secrets.APP_DOMAINS }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
