name: Release and deploy

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get short commit SHA
        id: shortsha
        run: echo "::set-output name=shortsha::$(git rev-parse --short HEAD)"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@master
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            server.args.VITE_APP_VER=${{ steps.shortsha.outputs.shortsha }}
          push: true

  deploy-bhidapa:
    name: Deploy to BHIDAPA
    needs: [release]
    environment: BHIDAPA
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup SSH identity
        run: |
          mkdir -p ~/.ssh && ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK
          ssh-add - <<< "${{ secrets.SSH_IDENTITY }}"
      - name: Create and use context
        run: |
          docker context create bhidapa --docker host=ssh://${{ secrets.USER }}@${{ secrets.HOST }}
          docker context use bhidapa
      - name: Pull
        run: docker compose pull
      - name: Down
        run: docker compose down || docker compose down # sometimes "down" fails, try 2 times
      # TODO: deploy database schema changes
      - name: Up
        env:
          APP_DOMAINS: ${{ secrets.APP_DOMAINS }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
