name: Server

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  # TODO: only release if web checks pass
  release:
    name: Release
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get short commit SHA
        id: shortsha
        run: echo "::set-output name=shortsha::$(git rev-parse --short HEAD)"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v2
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            server.args.VITE_APP_VER=${{ steps.shortsha.outputs.shortsha }}
          targets: server
          push: true
